language: rust
rust:
  - stable
  - 1.34.2
  - 1.32.0
  - beta
  - nightly
script:
  - cargo build --verbose $F
  - cargo test --verbose $F
matrix:
  include:
    - rust: stable
      env: TASK=rustfmt
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check
    - rust: stable
      env: F=--features=commandline
    - rust: beta
      env: F=--features=commandline
    - rust: nightly
      env: F=--features=commandline
  allow_failures:
    - rust: nightly
      env: F=--features=commandline
    - rust: nightly
      env:
