language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     script: cargo install -f rustfmt --vers 0.8.4 && PATH=${HOME}/.cargo/bin:$PATH cargo fmt
  allow_failures:
    - rust: nightly
