language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.23.0
  - 1.24.1
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt-preview
     script:
      - cargo fmt -- --write-mode=diff
   - rust: stable
     env: TASK=commandline
     script:
      - cargo test --features=commandline
  allow_failures:
    - rust: nightly
