language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.14.0
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     script: cargo install -f rustfmt && PATH=${HOME}/.cargo/bin:$PATH cargo fmt
  allow_failures:
    - rust: nightly
