[package]
name = "rsass"
version = "0.6.1-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]
categories = ["command-line-utilities", "web-programming"]
keywords = ["scss", "sass", "css"]
description = "Early-stage sass implementation in pure rust"
documentation = "https://docs.rs/rsass"
repository = "https://github.com/kaj/rsass"
readme = "README.md"
license = "MIT/Apache-2.0"

[[bin]]
name = "rsass"
doc = false

[features]
commandline = ["clap"]

[dependencies]
clap = { version = "^2.19", optional = true }
lazy_static = "1.0"
nom = "^3.2.0"
num-rational = { version = "^0.1", default-features = false }
num-traits = "^0.1"
rand = "^0.4"

[badges]
travis-ci = { repository = "kaj/rsass" }
