# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: [push, pull_request]

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo fmt --all -- --check

  # Run clippy on stable only
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo clippy --all-features

  # Run check on everything supported except where clippy is used instead.
  check:
    name: Check
    needs: rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
        include:
          - rust: 1.56.1
            only: --package rsass
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo check ${{ matrix.only }} --all-features

  test:
    name: Test Suite
    needs: [clippy, check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
          - 1.58.1
          - 1.56.1
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo test --package rsass

  commandline:
    name: Build cli
    needs: [clippy, check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo build --package rsass-cli
