# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: [push, pull_request]

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo fmt --all -- --check

  check:
    name: Clippy
    needs: rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - rsass
        rust:
          - stable
          - 1.56.1
          - nightly
        include:
          - package: spectest
            rust: stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo clippy --package ${{ matrix.package }} --all-features

  test:
    name: Test Suite
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
          - 1.58.1
          - 1.56.1
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo test --package rsass

  commandline:
    name: Build cli
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: echo "::add-matcher::.github/workflows/rust-problem-matcher.json"
      - run: cargo build --features=commandline
